# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expectedCal',
            new_name='expected_cal',
        ),
    ]
