# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171008_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expected_cal',
            field=models.IntegerField(default=0, help_text='User expected number of calories per day'),
        ),
    ]
