# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171016_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='calory',
            new_name='calorie',
        ),
    ]
